### PR TITLE
Add option for Pushshift API site

### LINKED ISSUE #682: 💡 Feature request: Add option for Pushshift API site
Last year it was requested to switch from reveddit.com to unddit.com as it was considered slow. While that was the case back then, it's the opposite now. Unddit isn't working well recently. Since both of them are interchangeable by just using the other domain it would be great to have an option like `LIBREDDIT_PUSHSHIFT_FRONTEND` where you can set the domain.

### PR DESCRIPTION
**Pull request by Tokarak**
^_^
Revival of #706. Fixes #682.

### CODE REVIEW

**Comment by Tokarak** [comment]
Looks like I merged an old commit 0_0

**Comment by Tokarak** [comment]
Now I had some 3rd party formater run; I'll try again later.

**Comment by r7l** [comment]
Isn't Pushshift dead by now? Reddit killed their access to the API and with the new API changes coming soon, there will most likely no replacement anytime soon.

**Comment by Tokarak** [comment]
I concede this Pr is not well timed. However it is better to have the functionality in the code-base incase an alternative ever pops up.

**Comment by Tokarak** [comment]
Suceeded by #812.

**Pull request closed without merging**
