### PR TITLE
switch to a distroless image; update docker-compose to reflect it.

### PR DESCRIPTION
**Pull request by kuanhulio**

### CODE REVIEW

**Comment by kuanhulio** [comment]
Sorry, it just completely blanked on my mind that distroless containers exist. Should've been included in #760, that's my bad.

**Comment by sigaloid** [comment]
Hi, I like this change. Do you have any specific numbers on the size/time saved on the image?

**Comment by kuanhulio** [comment]
Building from the main branch: `14.77 MB`
Building from this PR: `10.17 MB`

Not an insane difference as the main branch is already really optimized, but it's an improvement nonetheless.

Buildtimes are the same, however. I don't know enough Rust to optimize the buildtime anyway without some level of jank-ness.

**Comment by sigaloid** [comment]
Alright, great, this change is good with me. @Daniel-Valentine @spikecodes thoughts?

**Comment by kuanhulio** [comment]
In theory, we could also do a `scratch` build.

Building the `scratch` part results in a `7.71 MB` build.

**Pull request closed without merging**
