### PR TITLE
added comments to libreddit.service and .conf

### PR DESCRIPTION
**Pull request by Akanksh12**
Added comments to contrib/libreddit.conf so it is easier and more convenient to use.

### CODE REVIEW

**Comment by sigaloid** [comment]
Hi, just curious why you commented the default IP and port on contrib/libreddit.service? I think it would be good to leave it as the correct default port.

**Comment by Akanksh12** [comment]
I commented out the default IP and port in libreddit.service as they're already there in contrib/libreddit.conf. I agree that leaving it on the default port would be good, can you tell me how to fix that? I'm new to contributing. Should I make another PR?

**Comment by Akanksh12** [comment]
Hi, I've changed the default port to 12345

**Comment by sigaloid** [comment]
Thanks for the contribution! Merging.

**Pull request merged**
