### PR TITLE
Add Tokyo Night theme

### PR DESCRIPTION
**Pull request by pyrox0**
This adds the tokyo night theme.

### CODE REVIEW

**Comment by spikecodes** [comment]
Thanks for this theme! Is it based on the [VS Code theme](https://github.com/enkia/tokyo-night-vscode-theme)?
image
I feel like there is very little contrast except for the light outlines around post that contrast a lot with the very dark background

**Comment by spikecodes** [comment]
image
Maybe I'm seeing things but I felt like the VS Code theme had a lot more contrast

**Comment by ModdedGamers** [comment]
It is based on the VSCode theme. I'll work on the contrast.

**Comment by spikecodes** [comment]
Ok thanks!

**Comment by theHedgehog0** [comment]
This should be updated now.

Preview image below.
2022-07-25T11:31:33,693033482-04:00

**Review by skydiver1980 — APPROVED** [review]

**Pull request closed without merging**
