### PR TITLE
feat: add polls

### LINKED ISSUE #626: ✨ Feature parity: polls
## How does this feature work on Reddit?

poll. For most polls, while it’s open voting options only are visible, once it’s done you can see results (votes and percentages)
Some are logged-in only (but can you still fetch data?)

There are two pages: post page and poll page. Poll page (`/poll/:id`) is like post page, but comments aren’t displayed and there is a "comments" button that is a link to the post page.

## Describe how this could be implemented into Ferrit

Display total vote count, options, percentage and votes per option when available
I think there shouldn’t be poll page and poll page should redirect to poll page.

## Describe alternatives you've considered

We can also do a separate poll page with a link/button to post page with comments

## Additional context / screenshot

examples from /r/polls

reddit: poll page
image
poll not finished

https://www.reddit.com/r/polls/comments/s4ra3s/rpolls_2022_grand_prediction_tourney/
logged-in poll

image
https://www.reddit.com/r/polls/comments/qsrphu/have_you_ever_been_within_10_feet_of_a_cow/
finished poll

It has been implemented in teddit
libreddit issue: https://github.com/spikecodes/libreddit/issues/150

### PR DESCRIPTION
**Pull request by iTzBoboCz**
Fixes #626. You can only see polls, not vote. Still needs some polishing (time format, some CSS). Polls that aren't closed display the wrong values (0) because Reddit sends `vote_count` only for closed polls' options. I am not really friends with CSS so I welcome any ideas to improve the look.

### CODE REVIEW

**Review by sigaloid — COMMENTED** [review]
Some current comments I have :)

Also - I like the way it is, but maybe it could be changed to not display 0 - I think it is not helpful to see, if vote_count does not exist in the API return value.

**Comment by iTzBoboCz** [comment]
Thanks for the suggestions, I think it's ready now :)

**Comment by mikupls** [comment]
Hey, just wanted to say that I tested this today and it looks great! (The functionality at least, I haven't reviewed the code :))

I wonder if you considered making the "view poll" links work (the ones linking to `/poll/xxxx` directly). Of course, this could be done in a follow-up PR.

**Comment by sigaloid** [comment]
Stepped into repo and made one small change - resolving now_utc to a variable to avoid consecutive calls. Merging as soon as CI finishes, thank you so much for the contribution!

**Pull request merged**
