### PR TITLE
Make gated subreddits accessible by treating them as quarantined

### PR DESCRIPTION
**Pull request by domve**
Addresses #697, this would be at least a temporary fix to make gated communities such as r/drugs accessible, as right now there's no way to get past the `gated` messages.

### CODE REVIEW

**Comment by vlfldr** [comment]
This is an important change. Large swaths of reddit have been inaccessible via libreddit for roughly a month. Thanks for authoring it @domve and thanks in advance to whomever reviews it!

**Comment by sigaloid** [comment]
Thank you for this PR!

I think it might be a good idea to separate "quarantined" from "gated" - maybe pass the string into `quarantine` like so:

```rust
pub fn quarantine(req: Request<Body>, sub: String, restriction: String) -> Result<Response<Body>, String> {
	let wall = WallTemplate {
		title: format!("r/{} is {restriction}", sub),
```
The restriction is "quarantined" or "gated", so this works okay.

Also, there's a few other checks in the code for "quarantined" - perhaps those should be checked as well? (search `if msg == "quarantined"` in the code)

**Comment by domve** [comment]
Thanks for the heads up, added checks for the rest of those. 

I've also implemented the restriction thing in `quarantine`, I think it would be worth displaying the warning messages too but it might be neater for me to open a separate PR for it after this gets merged.

**Review by spikecodes — APPROVED** [review]
Looks good to me! Thanks for this PR

**Comment by Daniel-Valentine** [comment]
Looks good to me. Thanks for your contribution!

**Pull request merged**
